# Generated by Django 5.2.12 on 2026-03-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kaspi_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
